In [1]:
import pandas as pd

# Preprocessing data

In [2]:
#Read Training Data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train.head()

,Inv_Id,Vendor_Code,GL_Code,Inv_Amt,Item_Description,Product_Category
0,1,VENDOR-61,GL-6050100,6.973473,AETNA VARIABLE FUND - Apr-2002 - Store Managem...,CLASS-784
1,2,VENDOR-61,GL-6050100,25.053841,AETNA VARIABLE FUND - Nov-2000 - Store Managem...,CLASS-784
2,3,VENDOR-449,GL-6050100,53.573737,FAIRCHILD CORP - Nov-2001 - Store Management R...,CLASS-784
3,4,VENDOR-682,GL-6050100,67.388827,CALIFORNIA REAL ESTATE INVESTMENT TRUST - Aug-...,CLASS-784
4,5,VENDOR-682,GL-6050100,74.262047,CALIFORNIA REAL ESTATE INVESTMENT TRUST - Mar-...,CLASS-784

In [4]:
#Data Size
len(train)

5719

In [5]:
len(test)

2292

In [6]:
test.head()

,Inv_Id,Vendor_Code,GL_Code,Inv_Amt,Item_Description
0,6,VENDOR-1197,GL-6050100,10.916343,DESOTO INC - Jul-2008 - Store Management Real ...
1,12,VENDOR-792,GL-6050100,38.658772,CENTURY REALTY TRUST - Nov-2019 - Store Manage...
2,14,VENDOR-792,GL-6050100,46.780476,CENTURY REALTY TRUST - Jan-2006 - Store Manage...
3,18,VENDOR-792,GL-6050100,7.058866,CENTURY REALTY TRUST - Sep-2002 - Store Manage...
4,19,VENDOR-792,GL-6050100,32.931765,CENTURY REALTY TRUST - Nov-2018 - Store Manage...

In [7]:
out_Inv_Id = test['Inv_Id']

In [8]:
train.nunique()

Inv_Id              5719
Vendor_Code         1313
GL_Code                9
Inv_Amt             5719
Item_Description    5118
Product_Category      38
dtype: int64

In [9]:
#Check for missing values 
train.isna().sum()

Inv_Id              0
Vendor_Code         0
GL_Code             0
Inv_Amt             0
Item_Description    0
Product_Category    0
dtype: int64

In [10]:
#Increase the dimension of data and Convert to numeric data
def processData(data):
    data['Vendor_Code'] = data['Vendor_Code'].str.split("-", n = 0, expand = True)[1]
    data['GL_Code'] = data['GL_Code'].str.split("-", n = 0, expand = True)[1]
    new = data["Item_Description"].str.split(" - ", n = 2, expand = True)
    data["Company"]= new[0]
#     data["Month"]= new[1] 
    data["Description"]= new[2]
    month_Year = new[1].str.split("-", n = 1, expand = True)
    data["Month"] = month_Year[0]
#     data["Year"] = month_Year[1]
    data.drop(columns =["Item_Description","Inv_Id"], inplace = True) 
    return data

In [11]:
train = processData(train)
test = processData(test)

In [12]:
target = train['Product_Category'].str.split("-", n = 0, expand = True)[1]
train.drop(columns =["Product_Category"], inplace = True)

In [13]:
train.head()

,Vendor_Code,GL_Code,Inv_Amt,Company,Description,Month
0,61,6050100,6.973473,AETNA VARIABLE FUND,Store Management Real Estate Real Estate Servi...,Apr
1,61,6050100,25.053841,AETNA VARIABLE FUND,Store Management Real Estate Real Estate Servi...,Nov
2,449,6050100,53.573737,FAIRCHILD CORP,Store Management Real Estate Real Estate Servi...,Nov
3,682,6050100,67.388827,CALIFORNIA REAL ESTATE INVESTMENT TRUST,Store Management Real Estate Real Estate Servi...,Aug
4,682,6050100,74.262047,CALIFORNIA REAL ESTATE INVESTMENT TRUST,Store Management Real Estate Real Estate Servi...,Mar

In [14]:
test.head()

,Vendor_Code,GL_Code,Inv_Amt,Company,Description,Month
0,1197,6050100,10.916343,DESOTO INC,Store Management Real Estate Real Estate Servi...,Jul
1,792,6050100,38.658772,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Nov
2,792,6050100,46.780476,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Jan
3,792,6050100,7.058866,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Sep
4,792,6050100,32.931765,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Nov

In [15]:
train.nunique()

Vendor_Code    1313
GL_Code           9
Inv_Amt        5719
Company        1341
Description      38
Month            12
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import StandardScaler

In [17]:
Vendor_Code_Encoder = LabelEncoder()
GL_Code_Encoder = LabelEncoder()
Company_Encoder = LabelEncoder()
Month_Encoder = LabelEncoder()
year_Encoder = LabelEncoder()
Description_Encoder = LabelEncoder()
Product_Category_Encoder = LabelEncoder()
# Inv_Amt_Scalar = StandardScaler()

In [18]:
def dataEncoderfit(data):
    GL_Code_Encoder.fit(data['GL_Code'])
    Vendor_Code_Encoder.fit(data['Vendor_Code'])
    Company_Encoder.fit(data['Company'])
    Month_Encoder.fit(data['Month'])
#     year_Encoder.fit_transform(data['Year'])
    Description_Encoder.fit(data['Description'])
#     Inv_Amt_Scalar.fit(data['Inv_Amt'])

In [19]:
def dataEncoder(data):
    data['GL_Code'] = GL_Code_Encoder.transform(data['GL_Code'])
    data['Vendor_Code'] = Vendor_Code_Encoder.transform(data['Vendor_Code'])
    data['Company'] = Company_Encoder.transform(data['Company'])
    data['Month'] = Month_Encoder.transform(data['Month'])
#     data['Year'] = year_Encoder.fit_transform(data['Year'])
    data['Description'] = Description_Encoder.transform(data['Description'])
#     data['Inv_Amt'] = Inv_Amt_Scalar.transform(data['Inv_Amt'])
    return data

In [20]:
total_data_for_encoding = train.append(test)
dataEncoderfit(total_data_for_encoding)

In [21]:
train = dataEncoder(train)

In [22]:
len(train)

5719

In [23]:
train.head()

   Vendor_Code  GL_Code    Inv_Amt  Company  Description  Month
0         1128        2   6.973473       63           34      0
1         1128        2  25.053841       63           34      9
2          949        2  53.573737     1367           34      9
3         1208        2  67.388827      659           34      1
4         1208        2  74.262047      659           34      7

In [24]:
target.name = "Product_Category"
target.to_frame()

     Product_Category
0                 784
1                 784
2                 784
3                 784
4                 784
5                 784
6                 784
7                 784
8                 784
9                 784
10                784
11                784
12                784
13                784
14                784
15                784
16                784
17                489
18                489
19                489
20                489
21                913
22                913
23                368
24                368
25                913
26                816
27                816
28                629
29                629
...               ...
5689              230
5690              671
5691              913
5692              230
5693              913
5694              230
5695              230
5696              758
5697              571
5698              571
5699              571
5700              571
5701              571
5702              571
5703              571
5704              571
5705              571
5706              571
5707              571
5708              571
5709              571
5710              571
5711              571
5712              571
5713              571
5714              571
5715              571
5716              571
5717              571
5718              571

[5719 rows x 1 columns]

In [25]:
target = Product_Category_Encoder.fit_transform(target)

In [26]:
import numpy as np
np.unique(target,return_counts=True,axis=0)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37]),
 array([  34,   29,   26,  370,   34,   50,  107,  773,   79,   15,    4,
           7,  196,  464,  117, 1521,   22,   13,  115,   68,   13,   42,
          73,   42,  985,    3,  219,   27,    2,   19,   38,    2,   13,
          53,  107,    2,   27,    8], dtype=int64))

In [27]:
train.head()

   Vendor_Code  GL_Code    Inv_Amt  Company  Description  Month
0         1128        2   6.973473       63           34      0
1         1128        2  25.053841       63           34      9
2          949        2  53.573737     1367           34      9
3         1208        2  67.388827      659           34      1
4         1208        2  74.262047      659           34      7

In [28]:
train.nunique()

Vendor_Code    1313
GL_Code           9
Inv_Amt        5719
Company        1341
Description      38
Month            12
dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.05,random_state=1)

In [30]:
X_train.head()

      Vendor_Code  GL_Code    Inv_Amt  Company  Description  Month
2727         1421        3  68.884764     1037           37      4
2098          368        3  63.967626      140           37      3
2332          573        3  19.633461     1572           37      2
486           606        1   1.330082     1425           24     10
2820         1343        3  72.914602      775           37     11

# Model Building

In [31]:
import lightgbm as lgb

In [32]:
lgb_train = lgb.Dataset(X_train, y_train, free_raw_data=False)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train, free_raw_data=False)

In [33]:
#Hyperparameters

params = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class':38,
    'metric': 'multi_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 20
}

In [34]:
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=1000,
                valid_sets=lgb_eval,
                early_stopping_rounds=50,
                verbose_eval = True
               )

[1]	valid_0's multi_logloss: 1.98518
Training until validation scores don't improve for 50 rounds.
[2]	valid_0's multi_logloss: 1.79782
[3]	valid_0's multi_logloss: 1.64527
[4]	valid_0's multi_logloss: 1.52316
[5]	valid_0's multi_logloss: 1.41514
[6]	valid_0's multi_logloss: 1.32487
[7]	valid_0's multi_logloss: 1.2422
[8]	valid_0's multi_logloss: 1.1662
[9]	valid_0's multi_logloss: 1.09692
[10]	valid_0's multi_logloss: 1.03423
[11]	valid_0's multi_logloss: 0.976442
[12]	valid_0's multi_logloss: 0.923257
[13]	valid_0's multi_logloss: 0.874801
[14]	valid_0's multi_logloss: 0.829033
[15]	valid_0's multi_logloss: 0.786864
[16]	valid_0's multi_logloss: 0.746095
[17]	valid_0's multi_logloss: 0.708041
[18]	valid_0's multi_logloss: 0.672742
[19]	valid_0's multi_logloss: 0.639109
[20]	valid_0's multi_logloss: 0.607888
[21]	valid_0's multi_logloss: 0.578685
[22]	valid_0's multi_logloss: 0.551102
[23]	valid_0's multi_logloss: 0.524069
[24]	valid_0's multi_logloss: 0.498371
[25]	valid_0's multi_logloss: 0.474472
[26]	valid_0's multi_logloss: 0.451439
[27]	valid_0's multi_logloss: 0.430015
[28]	valid_0's multi_logloss: 0.409781
[29]	valid_0's multi_logloss: 0.390609
[30]	valid_0's multi_logloss: 0.373044
[31]	valid_0's multi_logloss: 0.355709
[32]	valid_0's multi_logloss: 0.339733
[33]	valid_0's multi_logloss: 0.324485
[34]	valid_0's multi_logloss: 0.309513
[35]	valid_0's multi_logloss: 0.295385
[36]	valid_0's multi_logloss: 0.2818
[37]	valid_0's multi_logloss: 0.268819
[38]	valid_0's multi_logloss: 0.256673
[39]	valid_0's multi_logloss: 0.244911
[40]	valid_0's multi_logloss: 0.234012
[41]	valid_0's multi_logloss: 0.223769
[42]	valid_0's multi_logloss: 0.213656
[43]	valid_0's multi_logloss: 0.204046
[44]	valid_0's multi_logloss: 0.194774
[45]	valid_0's multi_logloss: 0.185902
[46]	valid_0's multi_logloss: 0.177727
[47]	valid_0's multi_logloss: 0.169591
[48]	valid_0's multi_logloss: 0.162186
[49]	valid_0's multi_logloss: 0.155015
[50]	valid_0's multi_logloss: 0.148234
[51]	valid_0's multi_logloss: 0.141429
[52]	valid_0's multi_logloss: 0.135152
[53]	valid_0's multi_logloss: 0.128907
[54]	valid_0's multi_logloss: 0.123197
[55]	valid_0's multi_logloss: 0.117672
[56]	valid_0's multi_logloss: 0.11251
[57]	valid_0's multi_logloss: 0.107553
[58]	valid_0's multi_logloss: 0.102787
[59]	valid_0's multi_logloss: 0.0982137
[60]	valid_0's multi_logloss: 0.0938569
[61]	valid_0's multi_logloss: 0.0899236
[62]	valid_0's multi_logloss: 0.0861853
[63]	valid_0's multi_logloss: 0.0827092
[64]	valid_0's multi_logloss: 0.0792475
[65]	valid_0's multi_logloss: 0.0759751
[66]	valid_0's multi_logloss: 0.0727005
[67]	valid_0's multi_logloss: 0.0693941
[68]	valid_0's multi_logloss: 0.0663419
[69]	valid_0's multi_logloss: 0.0635103
[70]	valid_0's multi_logloss: 0.0607574
[71]	valid_0's multi_logloss: 0.0581559
[72]	valid_0's multi_logloss: 0.0558113
[73]	valid_0's multi_logloss: 0.0534183
[74]	valid_0's multi_logloss: 0.0511806
[75]	valid_0's multi_logloss: 0.0489562
[76]	valid_0's multi_logloss: 0.0470709
[77]	valid_0's multi_logloss: 0.0451508
[78]	valid_0's multi_logloss: 0.0434087
[79]	valid_0's multi_logloss: 0.041762
[80]	valid_0's multi_logloss: 0.0401143
[81]	valid_0's multi_logloss: 0.0384723
[82]	valid_0's multi_logloss: 0.036911
[83]	valid_0's multi_logloss: 0.0353643
[84]	valid_0's multi_logloss: 0.0339463
[85]	valid_0's multi_logloss: 0.0325332
[86]	valid_0's multi_logloss: 0.0312377
[87]	valid_0's multi_logloss: 0.0299701
[88]	valid_0's multi_logloss: 0.0288046
[89]	valid_0's multi_logloss: 0.0276918
[90]	valid_0's multi_logloss: 0.0265984
[91]	valid_0's multi_logloss: 0.0256448
[92]	valid_0's multi_logloss: 0.0246524
[93]	valid_0's multi_logloss: 0.0237872
[94]	valid_0's multi_logloss: 0.0228831
[95]	valid_0's multi_logloss: 0.0220502
[96]	valid_0's multi_logloss: 0.0211561
[97]	valid_0's multi_logloss: 0.0203103
[98]	valid_0's multi_logloss: 0.0195449
[99]	valid_0's multi_logloss: 0.0187741
[100]	valid_0's multi_logloss: 0.0179922
[101]	valid_0's multi_logloss: 0.0173133
[102]	valid_0's multi_logloss: 0.0166594
[103]	valid_0's multi_logloss: 0.0160234
[104]	valid_0's multi_logloss: 0.0153569
[105]	valid_0's multi_logloss: 0.0147568
[106]	valid_0's multi_logloss: 0.0142241
[107]	valid_0's multi_logloss: 0.0136341
[108]	valid_0's multi_logloss: 0.0130457
[109]	valid_0's multi_logloss: 0.0125671
[110]	valid_0's multi_logloss: 0.0120245
[111]	valid_0's multi_logloss: 0.0116363
[112]	valid_0's multi_logloss: 0.0111653
[113]	valid_0's multi_logloss: 0.0107287
[114]	valid_0's multi_logloss: 0.0103008
[115]	valid_0's multi_logloss: 0.0099098
[116]	valid_0's multi_logloss: 0.00951983
[117]	valid_0's multi_logloss: 0.00914644
[118]	valid_0's multi_logloss: 0.00880835
[119]	valid_0's multi_logloss: 0.00843849
[120]	valid_0's multi_logloss: 0.00811024
[121]	valid_0's multi_logloss: 0.00779569
[122]	valid_0's multi_logloss: 0.00750865
[123]	valid_0's multi_logloss: 0.00721132
[124]	valid_0's multi_logloss: 0.00700127
[125]	valid_0's multi_logloss: 0.00677742
[126]	valid_0's multi_logloss: 0.00650522
[127]	valid_0's multi_logloss: 0.0062614
[128]	valid_0's multi_logloss: 0.0060012
[129]	valid_0's multi_logloss: 0.00573494
[130]	valid_0's multi_logloss: 0.00550994
[131]	valid_0's multi_logloss: 0.00528566
[132]	valid_0's multi_logloss: 0.0050735
[133]	valid_0's multi_logloss: 0.00487425
[134]	valid_0's multi_logloss: 0.0046823
[135]	valid_0's multi_logloss: 0.0045262
[136]	valid_0's multi_logloss: 0.00440199
[137]	valid_0's multi_logloss: 0.00427025
[138]	valid_0's multi_logloss: 0.00413208
[139]	valid_0's multi_logloss: 0.00403716
[140]	valid_0's multi_logloss: 0.00391855
[141]	valid_0's multi_logloss: 0.00380924
[142]	valid_0's multi_logloss: 0.003656
[143]	valid_0's multi_logloss: 0.00350369
[144]	valid_0's multi_logloss: 0.00336781
[145]	valid_0's multi_logloss: 0.00327948
[146]	valid_0's multi_logloss: 0.00317653
[147]	valid_0's multi_logloss: 0.00310505
[148]	valid_0's multi_logloss: 0.00301222
[149]	valid_0's multi_logloss: 0.00290166
[150]	valid_0's multi_logloss: 0.00283561
[151]	valid_0's multi_logloss: 0.00272217
[152]	valid_0's multi_logloss: 0.00262537
[153]	valid_0's multi_logloss: 0.00251937
[154]	valid_0's multi_logloss: 0.00242103
[155]	valid_0's multi_logloss: 0.00232427
[156]	valid_0's multi_logloss: 0.00222875
[157]	valid_0's multi_logloss: 0.00213613
[158]	valid_0's multi_logloss: 0.0020491
[159]	valid_0's multi_logloss: 0.00200303
[160]	valid_0's multi_logloss: 0.00192851
[161]	valid_0's multi_logloss: 0.00184969
[162]	valid_0's multi_logloss: 0.00177704
[163]	valid_0's multi_logloss: 0.00170478
[164]	valid_0's multi_logloss: 0.00163885
[165]	valid_0's multi_logloss: 0.00159885
[166]	valid_0's multi_logloss: 0.00153253
[167]	valid_0's multi_logloss: 0.00147197
[168]	valid_0's multi_logloss: 0.00141587
[169]	valid_0's multi_logloss: 0.00135758
[170]	valid_0's multi_logloss: 0.00130493
[171]	valid_0's multi_logloss: 0.00124965
[172]	valid_0's multi_logloss: 0.00120563
[173]	valid_0's multi_logloss: 0.00117882
[174]	valid_0's multi_logloss: 0.00113714
[175]	valid_0's multi_logloss: 0.00111664
[176]	valid_0's multi_logloss: 0.00109106
[177]	valid_0's multi_logloss: 0.00106897
[178]	valid_0's multi_logloss: 0.00104562
[179]	valid_0's multi_logloss: 0.00102508
[180]	valid_0's multi_logloss: 0.00100623
[181]	valid_0's multi_logloss: 0.000995985
[182]	valid_0's multi_logloss: 0.000980948
[183]	valid_0's multi_logloss: 0.0009718
[184]	valid_0's multi_logloss: 0.000954823
[185]	valid_0's multi_logloss: 0.00094506
[186]	valid_0's multi_logloss: 0.000915265
[187]	valid_0's multi_logloss: 0.000880521
[188]	valid_0's multi_logloss: 0.000866053
[189]	valid_0's multi_logloss: 0.000855575
[190]	valid_0's multi_logloss: 0.000824811
[191]	valid_0's multi_logloss: 0.000811602
[192]	valid_0's multi_logloss: 0.000802224
[193]	valid_0's multi_logloss: 0.000790696
[194]	valid_0's multi_logloss: 0.000782236
[195]	valid_0's multi_logloss: 0.000771141
[196]	valid_0's multi_logloss: 0.000760799
[197]	valid_0's multi_logloss: 0.00075124
[198]	valid_0's multi_logloss: 0.00072187
[199]	valid_0's multi_logloss: 0.0007171
[200]	valid_0's multi_logloss: 0.00068686
[201]	valid_0's multi_logloss: 0.000662237

[202]	valid_0's multi_logloss: 0.000636024
[203]	valid_0's multi_logloss: 0.00061406
[204]	valid_0's multi_logloss: 0.000592539
[205]	valid_0's multi_logloss: 0.000572394
[206]	valid_0's multi_logloss: 0.000548772
[207]	valid_0's multi_logloss: 0.000527349
[208]	valid_0's multi_logloss: 0.000521966
[209]	valid_0's multi_logloss: 0.000499504
[210]	valid_0's multi_logloss: 0.000478988
[211]	valid_0's multi_logloss: 0.000474131
[212]	valid_0's multi_logloss: 0.000468624
[213]	valid_0's multi_logloss: 0.000449207
[214]	valid_0's multi_logloss: 0.000429184
[215]	valid_0's multi_logloss: 0.000409981
[216]	valid_0's multi_logloss: 0.000406884
[217]	valid_0's multi_logloss: 0.000403044
[218]	valid_0's multi_logloss: 0.000400207
[219]	valid_0's multi_logloss: 0.000397886
[220]	valid_0's multi_logloss: 0.00039553
[221]	valid_0's multi_logloss: 0.000382894
[222]	valid_0's multi_logloss: 0.00036978
[223]	valid_0's multi_logloss: 0.000357068
[224]	valid_0's multi_logloss: 0.000348245
[225]	valid_0's multi_logloss: 0.000336523
[226]	valid_0's multi_logloss: 0.000337201
[227]	valid_0's multi_logloss: 0.0003267
[228]	valid_0's multi_logloss: 0.000316812
[229]	valid_0's multi_logloss: 0.000306847
[230]	valid_0's multi_logloss: 0.000305126
[231]	valid_0's multi_logloss: 0.000295732
[232]	valid_0's multi_logloss: 0.00028719
[233]	valid_0's multi_logloss: 0.000280328
[234]	valid_0's multi_logloss: 0.000273363
[235]	valid_0's multi_logloss: 0.000265404
[236]	valid_0's multi_logloss: 0.000264234
[237]	valid_0's multi_logloss: 0.000259062
[238]	valid_0's multi_logloss: 0.00025393
[239]	valid_0's multi_logloss: 0.000249208
[240]	valid_0's multi_logloss: 0.0002465
[241]	valid_0's multi_logloss: 0.000240542
[242]	valid_0's multi_logloss: 0.000236404
[243]	valid_0's multi_logloss: 0.00023733
[244]	valid_0's multi_logloss: 0.000232864
[245]	valid_0's multi_logloss: 0.000230275
[246]	valid_0's multi_logloss: 0.000222235
[247]	valid_0's multi_logloss: 0.000216738
[248]	valid_0's multi_logloss: 0.000208936
[249]	valid_0's multi_logloss: 0.0002037
[250]	valid_0's multi_logloss: 0.00019883
[251]	valid_0's multi_logloss: 0.000193236
[252]	valid_0's multi_logloss: 0.000190504
[253]	valid_0's multi_logloss: 0.000185771
[254]	valid_0's multi_logloss: 0.000183109
[255]	valid_0's multi_logloss: 0.000182796
[256]	valid_0's multi_logloss: 0.000179343
[257]	valid_0's multi_logloss: 0.000175226
[258]	valid_0's multi_logloss: 0.000170737
[259]	valid_0's multi_logloss: 0.000167536
[260]	valid_0's multi_logloss: 0.000163895
[261]	valid_0's multi_logloss: 0.000161709
[262]	valid_0's multi_logloss: 0.000160075
[263]	valid_0's multi_logloss: 0.000156592
[264]	valid_0's multi_logloss: 0.000154797
[265]	valid_0's multi_logloss: 0.000154377
[266]	valid_0's multi_logloss: 0.00015353
[267]	valid_0's multi_logloss: 0.000150548
[268]	valid_0's multi_logloss: 0.000149356
[269]	valid_0's multi_logloss: 0.000148456
[270]	valid_0's multi_logloss: 0.000147596
[271]	valid_0's multi_logloss: 0.000146971
[272]	valid_0's multi_logloss: 0.00014319
[273]	valid_0's multi_logloss: 0.000142622
[274]	valid_0's multi_logloss: 0.000140038
[275]	valid_0's multi_logloss: 0.000137439
[276]	valid_0's multi_logloss: 0.00013473
[277]	valid_0's multi_logloss: 0.000132709
[278]	valid_0's multi_logloss: 0.000130654
[279]	valid_0's multi_logloss: 0.000128859
[280]	valid_0's multi_logloss: 0.000127241
[281]	valid_0's multi_logloss: 0.000125621
[282]	valid_0's multi_logloss: 0.000124836
[283]	valid_0's multi_logloss: 0.000123885
[284]	valid_0's multi_logloss: 0.000123285
[285]	valid_0's multi_logloss: 0.000122466
[286]	valid_0's multi_logloss: 0.000122546
[287]	valid_0's multi_logloss: 0.000122631
[288]	valid_0's multi_logloss: 0.000121612
[289]	valid_0's multi_logloss: 0.000122132
[290]	valid_0's multi_logloss: 0.000121167
[291]	valid_0's multi_logloss: 0.000120552
[292]	valid_0's multi_logloss: 0.00011882
[293]	valid_0's multi_logloss: 0.000117239
[294]	valid_0's multi_logloss: 0.000116825
[295]	valid_0's multi_logloss: 0.000115338
[296]	valid_0's multi_logloss: 0.000115661
[297]	valid_0's multi_logloss: 0.000116087
[298]	valid_0's multi_logloss: 0.000116544
[299]	valid_0's multi_logloss: 0.000116863
[300]	valid_0's multi_logloss: 0.000115846
[301]	valid_0's multi_logloss: 0.000114641
[302]	valid_0's multi_logloss: 0.000113357
[303]	valid_0's multi_logloss: 0.000112146
[304]	valid_0's multi_logloss: 0.000112378
[305]	valid_0's multi_logloss: 0.000111299
[306]	valid_0's multi_logloss: 0.000110267
[307]	valid_0's multi_logloss: 0.000110064
[308]	valid_0's multi_logloss: 0.000109683
[309]	valid_0's multi_logloss: 0.000108651
[310]	valid_0's multi_logloss: 0.000107702
[311]	valid_0's multi_logloss: 0.00010744
[312]	valid_0's multi_logloss: 0.000107278
[313]	valid_0's multi_logloss: 0.00010702
[314]	valid_0's multi_logloss: 0.000106762
[315]	valid_0's multi_logloss: 0.000107253
[316]	valid_0's multi_logloss: 0.000107789
[317]	valid_0's multi_logloss: 0.000108208
[318]	valid_0's multi_logloss: 0.000108624
[319]	valid_0's multi_logloss: 0.000109304
[320]	valid_0's multi_logloss: 0.000109814
[321]	valid_0's multi_logloss: 0.000108778
[322]	valid_0's multi_logloss: 0.00010929
[323]	valid_0's multi_logloss: 0.000108292
[324]	valid_0's multi_logloss: 0.000108874
[325]	valid_0's multi_logloss: 0.000107934
[326]	valid_0's multi_logloss: 0.000107906
[327]	valid_0's multi_logloss: 0.000107984
[328]	valid_0's multi_logloss: 0.000107948
[329]	valid_0's multi_logloss: 0.000108015
[330]	valid_0's multi_logloss: 0.000108054
[331]	valid_0's multi_logloss: 0.00010811
[332]	valid_0's multi_logloss: 0.000108299
[333]	valid_0's multi_logloss: 0.000108402
[334]	valid_0's multi_logloss: 0.000108583
[335]	valid_0's multi_logloss: 0.000108744
[336]	valid_0's multi_logloss: 0.00010818
[337]	valid_0's multi_logloss: 0.000108521
[338]	valid_0's multi_logloss: 0.000107824
[339]	valid_0's multi_logloss: 0.000107194
[340]	valid_0's multi_logloss: 0.000106577
[341]	valid_0's multi_logloss: 0.000106264
[342]	valid_0's multi_logloss: 0.000105557
[343]	valid_0's multi_logloss: 0.000105408
[344]	valid_0's multi_logloss: 0.000104838
[345]	valid_0's multi_logloss: 0.000104201
[346]	valid_0's multi_logloss: 0.000103647
[347]	valid_0's multi_logloss: 0.000103099
[348]	valid_0's multi_logloss: 0.000102523
[349]	valid_0's multi_logloss: 0.000101997
[350]	valid_0's multi_logloss: 0.000101429
[351]	valid_0's multi_logloss: 0.000101219
[352]	valid_0's multi_logloss: 0.000101014
[353]	valid_0's multi_logloss: 0.00010064
[354]	valid_0's multi_logloss: 0.000100411
[355]	valid_0's multi_logloss: 0.000100043
[356]	valid_0's multi_logloss: 9.93099e-05
[357]	valid_0's multi_logloss: 9.87713e-05
[358]	valid_0's multi_logloss: 9.8116e-05
[359]	valid_0's multi_logloss: 9.74836e-05
[360]	valid_0's multi_logloss: 9.70466e-05
[361]	valid_0's multi_logloss: 9.68981e-05
[362]	valid_0's multi_logloss: 9.72676e-05
[363]	valid_0's multi_logloss: 9.70915e-05
[364]	valid_0's multi_logloss: 9.69581e-05
[365]	valid_0's multi_logloss: 9.67996e-05
[366]	valid_0's multi_logloss: 9.7449e-05
[367]	valid_0's multi_logloss: 9.79764e-05
[368]	valid_0's multi_logloss: 9.84732e-05
[369]	valid_0's multi_logloss: 9.78639e-05
[370]	valid_0's multi_logloss: 9.83179e-05
[371]	valid_0's multi_logloss: 9.89261e-05
[372]	valid_0's multi_logloss: 9.94938e-05
[373]	valid_0's multi_logloss: 0.000100047
[374]	valid_0's multi_logloss: 0.000100594
[375]	valid_0's multi_logloss: 0.000101143
[376]	valid_0's multi_logloss: 0.000100964
[377]	valid_0's multi_logloss: 0.00010081
[378]	valid_0's multi_logloss: 0.000100506
[379]	valid_0's multi_logloss: 0.000100228
[380]	valid_0's multi_logloss: 9.99423e-05
[381]	valid_0's multi_logloss: 9.94597e-05
[382]	valid_0's multi_logloss: 9.99227e-05
[383]	valid_0's multi_logloss: 0.000100418
[384]	valid_0's multi_logloss: 0.000100882
[385]	valid_0's multi_logloss: 0.000101368
[386]	valid_0's multi_logloss: 0.000100826
[387]	valid_0's multi_logloss: 0.000101328
[388]	valid_0's multi_logloss: 0.0001015
[389]	valid_0's multi_logloss: 0.000102005
[390]	valid_0's multi_logloss: 0.000101476
[391]	valid_0's multi_logloss: 0.000100531
[392]	valid_0's multi_logloss: 9.9736e-05
[393]	valid_0's multi_logloss: 0.000100046

[394]	valid_0's multi_logloss: 0.00010034
[395]	valid_0's multi_logloss: 9.95095e-05
[396]	valid_0's multi_logloss: 9.93007e-05
[397]	valid_0's multi_logloss: 9.90899e-05
[398]	valid_0's multi_logloss: 9.85347e-05
[399]	valid_0's multi_logloss: 9.78649e-05
[400]	valid_0's multi_logloss: 9.78078e-05
[401]	valid_0's multi_logloss: 9.84679e-05
[402]	valid_0's multi_logloss: 9.87982e-05
[403]	valid_0's multi_logloss: 9.94299e-05
[404]	valid_0's multi_logloss: 9.97577e-05
[405]	valid_0's multi_logloss: 0.000100044
[406]	valid_0's multi_logloss: 9.9352e-05
[407]	valid_0's multi_logloss: 9.85156e-05
[408]	valid_0's multi_logloss: 9.77644e-05
[409]	valid_0's multi_logloss: 9.69385e-05
[410]	valid_0's multi_logloss: 9.61766e-05
[411]	valid_0's multi_logloss: 9.56189e-05
[412]	valid_0's multi_logloss: 9.51454e-05
[413]	valid_0's multi_logloss: 9.46721e-05
[414]	valid_0's multi_logloss: 9.41338e-05
[415]	valid_0's multi_logloss: 9.4175e-05
[416]	valid_0's multi_logloss: 9.38041e-05
[417]	valid_0's multi_logloss: 9.3317e-05
[418]	valid_0's multi_logloss: 9.28102e-05
[419]	valid_0's multi_logloss: 9.23449e-05
[420]	valid_0's multi_logloss: 9.29663e-05
[421]	valid_0's multi_logloss: 9.36919e-05
[422]	valid_0's multi_logloss: 9.44173e-05
[423]	valid_0's multi_logloss: 9.5123e-05
[424]	valid_0's multi_logloss: 9.57416e-05
[425]	valid_0's multi_logloss: 9.6441e-05
[426]	valid_0's multi_logloss: 9.67781e-05
[427]	valid_0's multi_logloss: 9.62915e-05
[428]	valid_0's multi_logloss: 9.66229e-05
[429]	valid_0's multi_logloss: 9.67931e-05
[430]	valid_0's multi_logloss: 9.71115e-05
[431]	valid_0's multi_logloss: 9.61466e-05
[432]	valid_0's multi_logloss: 9.52176e-05
[433]	valid_0's multi_logloss: 9.43217e-05
[434]	valid_0's multi_logloss: 9.34724e-05
[435]	valid_0's multi_logloss: 9.26537e-05
[436]	valid_0's multi_logloss: 9.21138e-05
[437]	valid_0's multi_logloss: 9.16067e-05
[438]	valid_0's multi_logloss: 9.11358e-05
[439]	valid_0's multi_logloss: 9.05536e-05
[440]	valid_0's multi_logloss: 8.99595e-05
[441]	valid_0's multi_logloss: 9.05022e-05
[442]	valid_0's multi_logloss: 9.10373e-05
[443]	valid_0's multi_logloss: 9.15745e-05
[444]	valid_0's multi_logloss: 9.21294e-05
[445]	valid_0's multi_logloss: 9.25455e-05
[446]	valid_0's multi_logloss: 9.22283e-05
[447]	valid_0's multi_logloss: 9.24276e-05
[448]	valid_0's multi_logloss: 9.25659e-05
[449]	valid_0's multi_logloss: 9.2769e-05
[450]	valid_0's multi_logloss: 9.24572e-05
[451]	valid_0's multi_logloss: 9.19603e-05
[452]	valid_0's multi_logloss: 9.14715e-05
[453]	valid_0's multi_logloss: 9.09897e-05
[454]	valid_0's multi_logloss: 9.05146e-05
[455]	valid_0's multi_logloss: 9.09392e-05
[456]	valid_0's multi_logloss: 9.19509e-05
[457]	valid_0's multi_logloss: 9.29711e-05
[458]	valid_0's multi_logloss: 9.3934e-05
[459]	valid_0's multi_logloss: 9.49327e-05
[460]	valid_0's multi_logloss: 9.59143e-05
[461]	valid_0's multi_logloss: 9.49706e-05
[462]	valid_0's multi_logloss: 9.407e-05
[463]	valid_0's multi_logloss: 9.3203e-05
[464]	valid_0's multi_logloss: 9.23797e-05
[465]	valid_0's multi_logloss: 9.21102e-05
[466]	valid_0's multi_logloss: 9.27279e-05
[467]	valid_0's multi_logloss: 9.33481e-05
[468]	valid_0's multi_logloss: 9.3958e-05
[469]	valid_0's multi_logloss: 9.45342e-05
[470]	valid_0's multi_logloss: 9.51207e-05
[471]	valid_0's multi_logloss: 9.46056e-05
[472]	valid_0's multi_logloss: 9.47645e-05
[473]	valid_0's multi_logloss: 9.42809e-05
[474]	valid_0's multi_logloss: 9.39251e-05
[475]	valid_0's multi_logloss: 9.40712e-05
[476]	valid_0's multi_logloss: 9.33704e-05
[477]	valid_0's multi_logloss: 9.26883e-05
[478]	valid_0's multi_logloss: 9.20402e-05
[479]	valid_0's multi_logloss: 9.1419e-05
[480]	valid_0's multi_logloss: 9.08052e-05
[481]	valid_0's multi_logloss: 9.0255e-05
[482]	valid_0's multi_logloss: 8.97108e-05
[483]	valid_0's multi_logloss: 8.95742e-05
[484]	valid_0's multi_logloss: 8.90917e-05
[485]	valid_0's multi_logloss: 8.86348e-05
[486]	valid_0's multi_logloss: 8.91984e-05
[487]	valid_0's multi_logloss: 8.90725e-05
[488]	valid_0's multi_logloss: 8.96073e-05
[489]	valid_0's multi_logloss: 9.01441e-05
[490]	valid_0's multi_logloss: 9.06769e-05
[491]	valid_0's multi_logloss: 9.17837e-05
[492]	valid_0's multi_logloss: 9.288e-05
[493]	valid_0's multi_logloss: 9.39474e-05
[494]	valid_0's multi_logloss: 9.50005e-05
[495]	valid_0's multi_logloss: 9.60554e-05
[496]	valid_0's multi_logloss: 9.62215e-05
[497]	valid_0's multi_logloss: 9.63951e-05
[498]	valid_0's multi_logloss: 9.64778e-05
[499]	valid_0's multi_logloss: 9.66469e-05
[500]	valid_0's multi_logloss: 9.67302e-05
[501]	valid_0's multi_logloss: 9.60493e-05
[502]	valid_0's multi_logloss: 9.53923e-05
[503]	valid_0's multi_logloss: 9.47553e-05
[504]	valid_0's multi_logloss: 9.41302e-05
[505]	valid_0's multi_logloss: 9.35319e-05
[506]	valid_0's multi_logloss: 9.33256e-05
[507]	valid_0's multi_logloss: 9.31175e-05
[508]	valid_0's multi_logloss: 9.29281e-05
[509]	valid_0's multi_logloss: 9.33348e-05
[510]	valid_0's multi_logloss: 9.31497e-05
[511]	valid_0's multi_logloss: 9.35628e-05
[512]	valid_0's multi_logloss: 9.39343e-05
[513]	valid_0's multi_logloss: 9.42992e-05
[514]	valid_0's multi_logloss: 9.46501e-05
[515]	valid_0's multi_logloss: 9.49581e-05
[516]	valid_0's multi_logloss: 9.51007e-05
[517]	valid_0's multi_logloss: 9.52886e-05
[518]	valid_0's multi_logloss: 9.54616e-05
[519]	valid_0's multi_logloss: 9.51089e-05
[520]	valid_0's multi_logloss: 9.52873e-05
[521]	valid_0's multi_logloss: 9.47894e-05
[522]	valid_0's multi_logloss: 9.44525e-05
[523]	valid_0's multi_logloss: 9.41055e-05
[524]	valid_0's multi_logloss: 9.36241e-05
[525]	valid_0's multi_logloss: 9.32929e-05
[526]	valid_0's multi_logloss: 9.38955e-05
[527]	valid_0's multi_logloss: 9.36723e-05
[528]	valid_0's multi_logloss: 9.42962e-05
[529]	valid_0's multi_logloss: 9.49133e-05
[530]	valid_0's multi_logloss: 9.54887e-05
[531]	valid_0's multi_logloss: 9.56868e-05
[532]	valid_0's multi_logloss: 9.58624e-05
[533]	valid_0's multi_logloss: 9.53397e-05
[534]	valid_0's multi_logloss: 9.55155e-05
[535]	valid_0's multi_logloss: 9.5024e-05
Early stopping, best iteration is:
[485]	valid_0's multi_logloss: 8.86348e-05

In [35]:
prediction = gbm.predict(X_test)

In [36]:
y_pred = [np.argmax(pred) for pred in prediction]

In [37]:
y_pred == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [38]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [39]:
print("Accuracy : "+str(accuracy_score(y_test, y_pred)))

Accuracy : 1.0

In [40]:
confusion_matrix(y_test, y_pred)

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 33,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 73,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0, 53,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2]], dtype=int64)

In [41]:
# gbm.save_model('model.txt')

# Test Data

In [42]:
test.head()

,Vendor_Code,GL_Code,Inv_Amt,Company,Description,Month
0,1197,6050100,10.916343,DESOTO INC,Store Management Real Estate Real Estate Servi...,Jul
1,792,6050100,38.658772,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Nov
2,792,6050100,46.780476,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Jan
3,792,6050100,7.058866,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Sep
4,792,6050100,32.931765,CENTURY REALTY TRUST,Store Management Real Estate Real Estate Servi...,Nov

In [43]:
test.isna().sum()

Vendor_Code    0
GL_Code        0
Inv_Amt        0
Company        0
Description    0
Month          0
dtype: int64

In [44]:
test = dataEncoder(test)

In [45]:
len(test)

2292

In [46]:
test.head()

   Vendor_Code  GL_Code    Inv_Amt  Company  Description  Month
0          220        2  10.916343     1131           34      5
1         1330        2  38.658772      766           34      9
2         1330        2  46.780476      766           34      4
3         1330        2   7.058866      766           34     11
4         1330        2  32.931765      766           34      9

In [47]:
actual_test_prediction = gbm.predict(test)

In [48]:
#probability of classification
actual_test_prediction

array([[1.90398189e-04, 1.29830673e-04, 5.84954614e-05, ...,
        2.54493833e-05, 1.65475020e-04, 7.90694640e-05],
       [4.37075056e-06, 3.48320240e-06, 1.61885224e-06, ...,
        7.31332227e-07, 3.81168492e-06, 1.73247468e-06],
       [5.04613144e-07, 6.70030615e-07, 2.98414654e-07, ...,
        1.75587279e-07, 7.24282587e-07, 2.89689448e-07],
       ...,
       [9.16153161e-08, 1.15821341e-07, 3.38714075e-08, ...,
        1.54144502e-08, 7.99621755e-08, 4.24975073e-08],
       [2.80561130e-06, 3.19498860e-06, 8.46041840e-07, ...,
        5.91115422e-07, 2.48121793e-06, 2.29218956e-06],
       [6.32972433e-07, 1.01652430e-06, 2.90357712e-07, ...,
        1.93676239e-07, 7.98695668e-07, 4.68727428e-07]])

In [49]:
encoded_actual_test_prediction = [np.argmax(pred) for pred in actual_test_prediction]

In [50]:
inverse_transformed_prediction = Product_Category_Encoder.inverse_transform(encoded_actual_test_prediction)

In [51]:
# data = {'Inv_Id': range(1 , len(inverse_transformed_prediction)+1),'Product_Category':inverse_transformed_prediction}
data = {'Inv_Id': out_Inv_Id,'Product_Category':inverse_transformed_prediction}

output = pd.DataFrame(data) 
output['Product_Category'] = 'CLASS-'+output['Product_Category'].astype(str)

In [52]:
output.to_csv(r'Prediction_Output.csv', index=False)