In [1]:
import pandas as pd

# Preprocessing data

In [2]:
#Read Training Data
train = pd.read_csv('Dataset/train.csv')
test = pd.read_csv('Dataset/test.csv')

In [3]:
train.head()

,Inv_Id,Vendor_Code,GL_Code,Inv_Amt,Item_Description,Product_Category
0,15001,VENDOR-1676,GL-6100410,83.24,Artworking/Typesetting Production Jun 2009 Cha...,CLASS-1963
1,15002,VENDOR-1883,GL-2182000,51.18,Auto Leasing Corporate Services Corning Inc /N...,CLASS-1250
2,15004,VENDOR-1999,GL-6050100,79.02,Store Management Lease/Rent Deltona Corp Real ...,CLASS-1274
3,15005,VENDOR-1771,GL-6101400,48.50,Store Construction General Requirements Coloni...,CLASS-1522
4,15006,VENDOR-1331,GL-2182000,63.35,Jul 2015 Aydin Corp Contingent Labor/Temp Labo...,CLASS-1376

In [4]:
#Data Size
len(train)

5566

In [5]:
out_Inv_Id = test['Inv_Id']

In [6]:
len(test)

2446

In [7]:
train.nunique()

Inv_Id              5566
Vendor_Code         1253
GL_Code                9
Inv_Amt             4258
Item_Description    5558
Product_Category      36
dtype: int64

In [8]:
#Check for missing values 
train.isna().sum()

Inv_Id              0
Vendor_Code         0
GL_Code             0
Inv_Amt             0
Item_Description    0
Product_Category    0
dtype: int64

In [9]:
#Increase the dimension of data and Convert to numeric data
def processData(data):
    data['Vendor_Code'] = data['Vendor_Code'].str.split("-", n = 0, expand = True)[1]
    data['GL_Code'] = data['GL_Code'].str.split("-", n = 0, expand = True)[1]
    data['Item_Description'] = data['Item_Description'].str.replace("/"," ")
    data.drop(columns =["Inv_Id"], inplace = True) 
    return data

In [10]:
target = train['Product_Category'].str.split("-", n = 0, expand = True)[1]
train.drop(columns =["Product_Category"], inplace = True)

In [11]:
train = processData(train)
test = processData(test)

In [12]:
train.head()

,Vendor_Code,GL_Code,Inv_Amt,Item_Description
0,1676,6100410,83.24,Artworking Typesetting Production Jun 2009 Cha...
1,1883,2182000,51.18,Auto Leasing Corporate Services Corning Inc N...
2,1999,6050100,79.02,Store Management Lease Rent Deltona Corp Real ...
3,1771,6101400,48.50,Store Construction General Requirements Coloni...
4,1331,2182000,63.35,Jul 2015 Aydin Corp Contingent Labor Temp Labo...

In [13]:
test.head()

,Vendor_Code,GL_Code,Inv_Amt,Item_Description
0,2513,6050310,56.13,Travel and Entertainment Miscellaneous Company...
1,1044,6101400,96.56,Final Site Clean Up Store Construction Advance...
2,1254,6101400,55.93,Arabian American Development Co Final Site Cle...
3,1331,2182000,32.62,Corporate Services Contingent Labor Temp Labor...
4,2513,6050310,25.81,Fortune National Corp Miscellaneous Company Ca...

In [14]:
train.nunique()

Vendor_Code         1253
GL_Code                9
Inv_Amt             4258
Item_Description    5558
dtype: int64

In [15]:
train.nunique()

Vendor_Code         1253
GL_Code                9
Inv_Amt             4258
Item_Description    5558
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import HashingVectorizer
# from sklearn.preprocessing import StandardScaler

In [17]:
Vendor_Code_Encoder = LabelEncoder()
GL_Code_Encoder = LabelEncoder()
Product_Category_Encoder = LabelEncoder()
hashV = HashingVectorizer(n_features=150)

In [18]:
def dataEncoderfit(data):
    GL_Code_Encoder.fit(data['GL_Code'])
    Vendor_Code_Encoder.fit(data['Vendor_Code'])
    hashV.fit(data['Item_Description'])

In [19]:
def dataEncoder(data):
    data['GL_Code'] = GL_Code_Encoder.transform(data['GL_Code'])
    data['Vendor_Code'] = Vendor_Code_Encoder.transform(data['Vendor_Code'])
    ret = pd.DataFrame.from_records(hashV.transform(data['Item_Description']).toarray())
    data.drop(columns =["Item_Description"], inplace = True) 
    return data.join(ret)

In [20]:
total_data_for_encoding = train.append(test)
dataEncoderfit(total_data_for_encoding)

In [21]:
train = dataEncoder(train)

In [22]:
train.nunique()

Vendor_Code    1253
GL_Code           9
Inv_Amt        4258
0                47
1                31
2                36
3                47
4                34
5                20
6                52
7                33
8                26
9                42
10               31
11               32
12               24
13               23
14               43
15               36
16               16
17               25
18               58
19               30
20               31
21               18
22               26
23               27
24               43
25               43
26               28
               ...
120              67
121              40
122              63
123              22
124               9
125              43
126              42
127              39
128              28
129              36
130              19
131              38
132              43
133              31
134              54
135              62
136              28
137              20
138              21
139              36
140              63
141              45
142              52
143              31
144              39
145              31
146              44
147              29
148              32
149              18
Length: 153, dtype: int64

In [23]:
len(train)

5566

In [24]:
train.head()

,Vendor_Code,GL_Code,Inv_Amt,0,1,2,3,4,5,6,...,140,141,142,143,144,145,146,147,148,149
0,676,5,83.24,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0
1,883,0,51.18,0.0,0.0,-0.408248,0.0,0.0,0.0,0.000000,...,0.000000,0.0,-0.204124,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0
2,999,2,79.02,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,-0.27735,0.0,0.000000,0.0,-0.27735,0.0
3,771,7,48.50,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,-0.458831,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0
4,331,0,63.35,0.0,0.0,0.000000,0.0,0.0,0.0,0.176777,...,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.176777,0.0,0.00000,0.0

In [25]:
target.name = "Product_Category"
target.to_frame()

     Product_Category
0                1963
1                1250
2                1274
3                1522
4                1376
5                1522
6                1758
7                1522
8                1963
9                1274
10               1758
11               1274
12               1274
13               2141
14               1522
15               1758
16               1522
17               1758
18               1963
19               1758
20               1429
21               1522
22               1274
23               1652
24               1758
25               1274
26               1249
27               1250
28               1758
29               1758
...               ...
5536             1274
5537             1274
5538             1274
5539             1758
5540             1758
5541             1309
5542             1758
5543             1758
5544             1274
5545             1963
5546             1567
5547             1963
5548             1522
5549             2241
5550             1522
5551             2003
5552             2112
5553             1376
5554             1250
5555             1758
5556             1274
5557             1376
5558             1567
5559             1758
5560             1522
5561             1376
5562             1870
5563             1721
5564             1652
5565             1758

[5566 rows x 1 columns]

In [26]:
target = Product_Category_Encoder.fit_transform(target)

In [27]:
import numpy as np
# np.unique(target,return_counts=True,axis=0)

In [28]:
num_class = len(np.unique(target))

In [29]:
target

array([25,  2,  3, ..., 14, 12, 15])

# Test Train Split among Train data

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.001,random_state=1)

# Model Building

In [31]:
import lightgbm as lgb

In [32]:
lgb_train = lgb.Dataset(X_train, y_train, free_raw_data=False)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train, free_raw_data=False)

In [33]:
#Hyperparameters

params = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class':num_class,
    'metric': 'multi_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 20
}

In [34]:
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=1000,
                valid_sets=lgb_eval,
                early_stopping_rounds=50,
                verbose_eval = True
               )

[1]	valid_0's multi_logloss: 1.55372
Training until validation scores don't improve for 50 rounds.
[2]	valid_0's multi_logloss: 1.43961
[3]	valid_0's multi_logloss: 1.33997
[4]	valid_0's multi_logloss: 1.25136
[5]	valid_0's multi_logloss: 1.17081
[6]	valid_0's multi_logloss: 1.09802
[7]	valid_0's multi_logloss: 1.03126
[8]	valid_0's multi_logloss: 0.970092
[9]	valid_0's multi_logloss: 0.913296
[10]	valid_0's multi_logloss: 0.860763
[11]	valid_0's multi_logloss: 0.812275
[12]	valid_0's multi_logloss: 0.767065
[13]	valid_0's multi_logloss: 0.724674
[14]	valid_0's multi_logloss: 0.685177
[15]	valid_0's multi_logloss: 0.648274
[16]	valid_0's multi_logloss: 0.61361
[17]	valid_0's multi_logloss: 0.581202
[18]	valid_0's multi_logloss: 0.550575
[19]	valid_0's multi_logloss: 0.521805
[20]	valid_0's multi_logloss: 0.494614
[21]	valid_0's multi_logloss: 0.468965
[22]	valid_0's multi_logloss: 0.444826
[23]	valid_0's multi_logloss: 0.421965
[24]	valid_0's multi_logloss: 0.400349
[25]	valid_0's multi_logloss: 0.379959
[26]	valid_0's multi_logloss: 0.360613
[27]	valid_0's multi_logloss: 0.342301
[28]	valid_0's multi_logloss: 0.324975
[29]	valid_0's multi_logloss: 0.308464
[30]	valid_0's multi_logloss: 0.292945
[31]	valid_0's multi_logloss: 0.278237
[32]	valid_0's multi_logloss: 0.264287
[33]	valid_0's multi_logloss: 0.251077
[34]	valid_0's multi_logloss: 0.23855
[35]	valid_0's multi_logloss: 0.226652
[36]	valid_0's multi_logloss: 0.215375
[37]	valid_0's multi_logloss: 0.20468
[38]	valid_0's multi_logloss: 0.194509
[39]	valid_0's multi_logloss: 0.184854
[40]	valid_0's multi_logloss: 0.175706
[41]	valid_0's multi_logloss: 0.167018
[42]	valid_0's multi_logloss: 0.158758
[43]	valid_0's multi_logloss: 0.150921
[44]	valid_0's multi_logloss: 0.143434
[45]	valid_0's multi_logloss: 0.136376
[46]	valid_0's multi_logloss: 0.129648
[47]	valid_0's multi_logloss: 0.123254
[48]	valid_0's multi_logloss: 0.117182
[49]	valid_0's multi_logloss: 0.111414
[50]	valid_0's multi_logloss: 0.105924
[51]	valid_0's multi_logloss: 0.100714
[52]	valid_0's multi_logloss: 0.0957507
[53]	valid_0's multi_logloss: 0.0910445
[54]	valid_0's multi_logloss: 0.0865763
[55]	valid_0's multi_logloss: 0.0823269
[56]	valid_0's multi_logloss: 0.0782711
[57]	valid_0's multi_logloss: 0.0744289
[58]	valid_0's multi_logloss: 0.0707726
[59]	valid_0's multi_logloss: 0.0673001
[60]	valid_0's multi_logloss: 0.0639968
[61]	valid_0's multi_logloss: 0.0608608
[62]	valid_0's multi_logloss: 0.0578785
[63]	valid_0's multi_logloss: 0.0550434
[64]	valid_0's multi_logloss: 0.0523482
[65]	valid_0's multi_logloss: 0.0497853
[66]	valid_0's multi_logloss: 0.04735
[67]	valid_0's multi_logloss: 0.0450388
[68]	valid_0's multi_logloss: 0.0428361
[69]	valid_0's multi_logloss: 0.0407421
[70]	valid_0's multi_logloss: 0.0387515
[71]	valid_0's multi_logloss: 0.0368555
[72]	valid_0's multi_logloss: 0.035049
[73]	valid_0's multi_logloss: 0.0333349
[74]	valid_0's multi_logloss: 0.0317046
[75]	valid_0's multi_logloss: 0.0301544
[76]	valid_0's multi_logloss: 0.0286797
[77]	valid_0's multi_logloss: 0.0272765
[78]	valid_0's multi_logloss: 0.0259453
[79]	valid_0's multi_logloss: 0.0246773
[80]	valid_0's multi_logloss: 0.0234708
[81]	valid_0's multi_logloss: 0.0223233
[82]	valid_0's multi_logloss: 0.0212343
[83]	valid_0's multi_logloss: 0.0201973
[84]	valid_0's multi_logloss: 0.0192115
[85]	valid_0's multi_logloss: 0.0182733
[86]	valid_0's multi_logloss: 0.0173792
[87]	valid_0's multi_logloss: 0.0165314
[88]	valid_0's multi_logloss: 0.0157229
[89]	valid_0's multi_logloss: 0.0149563
[90]	valid_0's multi_logloss: 0.0142249
[91]	valid_0's multi_logloss: 0.0135305
[92]	valid_0's multi_logloss: 0.0128698
[93]	valid_0's multi_logloss: 0.0122414
[94]	valid_0's multi_logloss: 0.0116437
[95]	valid_0's multi_logloss: 0.0110752
[96]	valid_0's multi_logloss: 0.0105343
[97]	valid_0's multi_logloss: 0.0100198
[98]	valid_0's multi_logloss: 0.00953053
[99]	valid_0's multi_logloss: 0.00906516
[100]	valid_0's multi_logloss: 0.00862324
[101]	valid_0's multi_logloss: 0.00820239
[102]	valid_0's multi_logloss: 0.00780177
[103]	valid_0's multi_logloss: 0.00742069
[104]	valid_0's multi_logloss: 0.00705829
[105]	valid_0's multi_logloss: 0.00671357
[106]	valid_0's multi_logloss: 0.00638562
[107]	valid_0's multi_logloss: 0.00607397
[108]	valid_0's multi_logloss: 0.0057773
[109]	valid_0's multi_logloss: 0.00549535
[110]	valid_0's multi_logloss: 0.00522762
[111]	valid_0's multi_logloss: 0.00497242
[112]	valid_0's multi_logloss: 0.0047297
[113]	valid_0's multi_logloss: 0.00449885
[114]	valid_0's multi_logloss: 0.00427925
[115]	valid_0's multi_logloss: 0.00407039
[116]	valid_0's multi_logloss: 0.00387216
[117]	valid_0's multi_logloss: 0.00368321
[118]	valid_0's multi_logloss: 0.00350379
[119]	valid_0's multi_logloss: 0.00333317
[120]	valid_0's multi_logloss: 0.00317088
[121]	valid_0's multi_logloss: 0.00301821
[122]	valid_0's multi_logloss: 0.00287263
[123]	valid_0's multi_logloss: 0.0027344
[124]	valid_0's multi_logloss: 0.00260131
[125]	valid_0's multi_logloss: 0.00247624
[126]	valid_0's multi_logloss: 0.00235545
[127]	valid_0's multi_logloss: 0.00224054
[128]	valid_0's multi_logloss: 0.00213124
[129]	valid_0's multi_logloss: 0.00202728
[130]	valid_0's multi_logloss: 0.00192838
[131]	valid_0's multi_logloss: 0.00183464
[132]	valid_0's multi_logloss: 0.00174546
[133]	valid_0's multi_logloss: 0.00166032
[134]	valid_0's multi_logloss: 0.00157963
[135]	valid_0's multi_logloss: 0.00150285
[136]	valid_0's multi_logloss: 0.00142954
[137]	valid_0's multi_logloss: 0.0013598
[138]	valid_0's multi_logloss: 0.00129347
[139]	valid_0's multi_logloss: 0.00123063
[140]	valid_0's multi_logloss: 0.00117086
[141]	valid_0's multi_logloss: 0.00111381
[142]	valid_0's multi_logloss: 0.00105954
[143]	valid_0's multi_logloss: 0.00100793
[144]	valid_0's multi_logloss: 0.000958821
[145]	valid_0's multi_logloss: 0.000912234
[146]	valid_0's multi_logloss: 0.00086773
[147]	valid_0's multi_logloss: 0.0008254
[148]	valid_0's multi_logloss: 0.000785135
[149]	valid_0's multi_logloss: 0.000746833
[150]	valid_0's multi_logloss: 0.000710503
[151]	valid_0's multi_logloss: 0.000677286
[152]	valid_0's multi_logloss: 0.000644347
[153]	valid_0's multi_logloss: 0.000614268
[154]	valid_0's multi_logloss: 0.000585534
[155]	valid_0's multi_logloss: 0.000557064
[156]	valid_0's multi_logloss: 0.000529893
[157]	valid_0's multi_logloss: 0.000504047
[158]	valid_0's multi_logloss: 0.000479463
[159]	valid_0's multi_logloss: 0.000456077
[160]	valid_0's multi_logloss: 0.000433832
[161]	valid_0's multi_logloss: 0.000412675
[162]	valid_0's multi_logloss: 0.000392548
[163]	valid_0's multi_logloss: 0.000373405
[164]	valid_0's multi_logloss: 0.000355195
[165]	valid_0's multi_logloss: 0.000337918
[166]	valid_0's multi_logloss: 0.000321465
[167]	valid_0's multi_logloss: 0.000305815
[168]	valid_0's multi_logloss: 0.000290929
[169]	valid_0's multi_logloss: 0.000276768
[170]	valid_0's multi_logloss: 0.000263335
[171]	valid_0's multi_logloss: 0.000250499
[172]	valid_0's multi_logloss: 0.000238288
[173]	valid_0's multi_logloss: 0.000226708
[174]	valid_0's multi_logloss: 0.000215658
[175]	valid_0's multi_logloss: 0.000205145
[176]	valid_0's multi_logloss: 0.000195168
[177]	valid_0's multi_logloss: 0.000185682
[178]	valid_0's multi_logloss: 0.000176655
[179]	valid_0's multi_logloss: 0.000168039
[180]	valid_0's multi_logloss: 0.000159874
[181]	valid_0's multi_logloss: 0.000152098
[182]	valid_0's multi_logloss: 0.000144684
[183]	valid_0's multi_logloss: 0.000137659
[184]	valid_0's multi_logloss: 0.000130975
[185]	valid_0's multi_logloss: 0.000124626
[186]	valid_0's multi_logloss: 0.000118563
[187]	valid_0's multi_logloss: 0.000112784
[188]	valid_0's multi_logloss: 0.000107298
[189]	valid_0's multi_logloss: 0.000102068
[190]	valid_0's multi_logloss: 9.71039e-05
[191]	valid_0's multi_logloss: 9.23834e-05
[192]	valid_0's multi_logloss: 8.78941e-05
[193]	valid_0's multi_logloss: 8.36387e-05
[194]	valid_0's multi_logloss: 7.95737e-05
[195]	valid_0's multi_logloss: 7.57092e-05
[196]	valid_0's multi_logloss: 7.20179e-05
[197]	valid_0's multi_logloss: 6.85098e-05
[198]	valid_0's multi_logloss: 6.51879e-05
[199]	valid_0's multi_logloss: 6.2012e-05
[200]	valid_0's multi_logloss: 5.89915e-05
[201]	valid_0's multi_logloss: 5.61219e-05

[202]	valid_0's multi_logloss: 5.34059e-05
[203]	valid_0's multi_logloss: 5.08092e-05
[204]	valid_0's multi_logloss: 4.83523e-05
[205]	valid_0's multi_logloss: 4.6055e-05
[206]	valid_0's multi_logloss: 4.38116e-05
[207]	valid_0's multi_logloss: 4.16784e-05
[208]	valid_0's multi_logloss: 3.9651e-05
[209]	valid_0's multi_logloss: 3.77272e-05
[210]	valid_0's multi_logloss: 3.58977e-05
[211]	valid_0's multi_logloss: 3.41495e-05
[212]	valid_0's multi_logloss: 3.2497e-05
[213]	valid_0's multi_logloss: 3.09155e-05
[214]	valid_0's multi_logloss: 2.94251e-05
[215]	valid_0's multi_logloss: 2.79993e-05
[216]	valid_0's multi_logloss: 2.66511e-05
[217]	valid_0's multi_logloss: 2.54031e-05
[218]	valid_0's multi_logloss: 2.41814e-05
[219]	valid_0's multi_logloss: 2.3051e-05
[220]	valid_0's multi_logloss: 2.1942e-05
[221]	valid_0's multi_logloss: 2.09252e-05
[222]	valid_0's multi_logloss: 1.99595e-05
[223]	valid_0's multi_logloss: 1.90173e-05
[224]	valid_0's multi_logloss: 1.81165e-05
[225]	valid_0's multi_logloss: 1.72513e-05
[226]	valid_0's multi_logloss: 1.64341e-05
[227]	valid_0's multi_logloss: 1.56531e-05
[228]	valid_0's multi_logloss: 1.49098e-05
[229]	valid_0's multi_logloss: 1.42165e-05
[230]	valid_0's multi_logloss: 1.3553e-05
[231]	valid_0's multi_logloss: 1.29172e-05
[232]	valid_0's multi_logloss: 1.23154e-05
[233]	valid_0's multi_logloss: 1.17432e-05
[234]	valid_0's multi_logloss: 1.12086e-05
[235]	valid_0's multi_logloss: 1.06991e-05
[236]	valid_0's multi_logloss: 1.0209e-05
[237]	valid_0's multi_logloss: 9.74217e-06
[238]	valid_0's multi_logloss: 9.29935e-06
[239]	valid_0's multi_logloss: 8.89057e-06
[240]	valid_0's multi_logloss: 8.49739e-06
[241]	valid_0's multi_logloss: 8.12138e-06
[242]	valid_0's multi_logloss: 7.763e-06
[243]	valid_0's multi_logloss: 7.42185e-06
[244]	valid_0's multi_logloss: 7.09542e-06
[245]	valid_0's multi_logloss: 6.78456e-06
[246]	valid_0's multi_logloss: 6.49052e-06
[247]	valid_0's multi_logloss: 6.20898e-06
[248]	valid_0's multi_logloss: 5.94101e-06
[249]	valid_0's multi_logloss: 5.68614e-06
[250]	valid_0's multi_logloss: 5.44236e-06
[251]	valid_0's multi_logloss: 5.2092e-06
[252]	valid_0's multi_logloss: 4.98613e-06
[253]	valid_0's multi_logloss: 4.77297e-06
[254]	valid_0's multi_logloss: 4.56996e-06
[255]	valid_0's multi_logloss: 4.37666e-06
[256]	valid_0's multi_logloss: 4.19437e-06
[257]	valid_0's multi_logloss: 4.02186e-06
[258]	valid_0's multi_logloss: 3.85977e-06
[259]	valid_0's multi_logloss: 3.7014e-06
[260]	valid_0's multi_logloss: 3.55178e-06
[261]	valid_0's multi_logloss: 3.40785e-06
[262]	valid_0's multi_logloss: 3.27069e-06
[263]	valid_0's multi_logloss: 3.13906e-06
[264]	valid_0's multi_logloss: 3.01286e-06
[265]	valid_0's multi_logloss: 2.89357e-06
[266]	valid_0's multi_logloss: 2.77862e-06
[267]	valid_0's multi_logloss: 2.66972e-06
[268]	valid_0's multi_logloss: 2.56613e-06
[269]	valid_0's multi_logloss: 2.4667e-06
[270]	valid_0's multi_logloss: 2.3718e-06
[271]	valid_0's multi_logloss: 2.28068e-06
[272]	valid_0's multi_logloss: 2.19355e-06
[273]	valid_0's multi_logloss: 2.11113e-06
[274]	valid_0's multi_logloss: 2.03236e-06
[275]	valid_0's multi_logloss: 1.95819e-06
[276]	valid_0's multi_logloss: 1.88967e-06
[277]	valid_0's multi_logloss: 1.82362e-06
[278]	valid_0's multi_logloss: 1.76012e-06
[279]	valid_0's multi_logloss: 1.69977e-06
[280]	valid_0's multi_logloss: 1.64073e-06
[281]	valid_0's multi_logloss: 1.58563e-06
[282]	valid_0's multi_logloss: 1.5325e-06
[283]	valid_0's multi_logloss: 1.48306e-06
[284]	valid_0's multi_logloss: 1.43559e-06
[285]	valid_0's multi_logloss: 1.38821e-06
[286]	valid_0's multi_logloss: 1.34317e-06
[287]	valid_0's multi_logloss: 1.29961e-06
[288]	valid_0's multi_logloss: 1.26091e-06
[289]	valid_0's multi_logloss: 1.22097e-06
[290]	valid_0's multi_logloss: 1.18357e-06
[291]	valid_0's multi_logloss: 1.14838e-06
[292]	valid_0's multi_logloss: 1.11324e-06
[293]	valid_0's multi_logloss: 1.08091e-06
[294]	valid_0's multi_logloss: 1.05038e-06
[295]	valid_0's multi_logloss: 1.02039e-06
[296]	valid_0's multi_logloss: 9.90739e-07
[297]	valid_0's multi_logloss: 9.6231e-07
[298]	valid_0's multi_logloss: 9.34839e-07
[299]	valid_0's multi_logloss: 9.08245e-07
[300]	valid_0's multi_logloss: 8.8262e-07
[301]	valid_0's multi_logloss: 8.56945e-07
[302]	valid_0's multi_logloss: 8.32291e-07
[303]	valid_0's multi_logloss: 8.08171e-07
[304]	valid_0's multi_logloss: 7.84994e-07
[305]	valid_0's multi_logloss: 7.62874e-07
[306]	valid_0's multi_logloss: 7.42123e-07
[307]	valid_0's multi_logloss: 7.20977e-07
[308]	valid_0's multi_logloss: 7.00583e-07
[309]	valid_0's multi_logloss: 6.80845e-07
[310]	valid_0's multi_logloss: 6.61806e-07
[311]	valid_0's multi_logloss: 6.44364e-07
[312]	valid_0's multi_logloss: 6.2637e-07
[313]	valid_0's multi_logloss: 6.1008e-07
[314]	valid_0's multi_logloss: 5.93274e-07
[315]	valid_0's multi_logloss: 5.78488e-07
[316]	valid_0's multi_logloss: 5.63058e-07
[317]	valid_0's multi_logloss: 5.4771e-07
[318]	valid_0's multi_logloss: 5.32842e-07
[319]	valid_0's multi_logloss: 5.18973e-07
[320]	valid_0's multi_logloss: 5.08575e-07
[321]	valid_0's multi_logloss: 4.98393e-07
[322]	valid_0's multi_logloss: 4.89436e-07
[323]	valid_0's multi_logloss: 4.79855e-07
[324]	valid_0's multi_logloss: 4.70674e-07
[325]	valid_0's multi_logloss: 4.62953e-07
[326]	valid_0's multi_logloss: 4.55432e-07
[327]	valid_0's multi_logloss: 4.48145e-07
[328]	valid_0's multi_logloss: 4.40675e-07
[329]	valid_0's multi_logloss: 4.33233e-07
[330]	valid_0's multi_logloss: 4.28127e-07
[331]	valid_0's multi_logloss: 4.2365e-07
[332]	valid_0's multi_logloss: 4.193e-07
[333]	valid_0's multi_logloss: 4.15075e-07
[334]	valid_0's multi_logloss: 4.1097e-07
[335]	valid_0's multi_logloss: 4.1097e-07
[336]	valid_0's multi_logloss: 4.1097e-07
[337]	valid_0's multi_logloss: 4.1097e-07
[338]	valid_0's multi_logloss: 4.1097e-07
[339]	valid_0's multi_logloss: 4.1097e-07
[340]	valid_0's multi_logloss: 4.1097e-07
[341]	valid_0's multi_logloss: 4.1097e-07
[342]	valid_0's multi_logloss: 4.1097e-07
[343]	valid_0's multi_logloss: 4.1097e-07
[344]	valid_0's multi_logloss: 4.1097e-07
[345]	valid_0's multi_logloss: 4.1097e-07
[346]	valid_0's multi_logloss: 4.1097e-07
[347]	valid_0's multi_logloss: 4.1097e-07
[348]	valid_0's multi_logloss: 4.1097e-07
[349]	valid_0's multi_logloss: 4.1097e-07
[350]	valid_0's multi_logloss: 4.1097e-07
[351]	valid_0's multi_logloss: 4.1097e-07
[352]	valid_0's multi_logloss: 4.1097e-07
[353]	valid_0's multi_logloss: 4.1097e-07
[354]	valid_0's multi_logloss: 4.1097e-07
[355]	valid_0's multi_logloss: 4.1097e-07
[356]	valid_0's multi_logloss: 4.1097e-07
[357]	valid_0's multi_logloss: 4.1097e-07
[358]	valid_0's multi_logloss: 4.1097e-07
[359]	valid_0's multi_logloss: 4.1097e-07
[360]	valid_0's multi_logloss: 4.1097e-07
[361]	valid_0's multi_logloss: 4.1097e-07
[362]	valid_0's multi_logloss: 4.1097e-07
[363]	valid_0's multi_logloss: 4.1097e-07
[364]	valid_0's multi_logloss: 4.1097e-07
[365]	valid_0's multi_logloss: 4.1097e-07
[366]	valid_0's multi_logloss: 4.1097e-07
[367]	valid_0's multi_logloss: 4.1097e-07
[368]	valid_0's multi_logloss: 4.1097e-07
[369]	valid_0's multi_logloss: 4.1097e-07
[370]	valid_0's multi_logloss: 4.1097e-07
[371]	valid_0's multi_logloss: 4.1097e-07
[372]	valid_0's multi_logloss: 4.1097e-07
[373]	valid_0's multi_logloss: 4.1097e-07
[374]	valid_0's multi_logloss: 4.1097e-07
[375]	valid_0's multi_logloss: 4.1097e-07
[376]	valid_0's multi_logloss: 4.1097e-07
[377]	valid_0's multi_logloss: 4.1097e-07
[378]	valid_0's multi_logloss: 4.1097e-07
[379]	valid_0's multi_logloss: 4.1097e-07
[380]	valid_0's multi_logloss: 4.1097e-07
[381]	valid_0's multi_logloss: 4.1097e-07
[382]	valid_0's multi_logloss: 4.1097e-07
[383]	valid_0's multi_logloss: 4.1097e-07
[384]	valid_0's multi_logloss: 4.1097e-07
Early stopping, best iteration is:
[334]	valid_0's multi_logloss: 4.1097e-07

In [35]:
prediction = gbm.predict(X_test)

In [36]:
y_pred = [np.argmax(pred) for pred in prediction]

In [37]:
y_pred == y_test

array([ True,  True,  True,  True,  True,  True])

In [38]:
from sklearn.metrics import accuracy_score
# from sklearn.metrics import confusion_matrix

In [39]:
print("Accuracy : "+str(accuracy_score(y_test, y_pred)))

Accuracy : 1.0

In [40]:
# confusion_matrix(y_test, y_pred)

# Test Data

In [41]:
test.head()

,Vendor_Code,GL_Code,Inv_Amt,Item_Description
0,2513,6050310,56.13,Travel and Entertainment Miscellaneous Company...
1,1044,6101400,96.56,Final Site Clean Up Store Construction Advance...
2,1254,6101400,55.93,Arabian American Development Co Final Site Cle...
3,1331,2182000,32.62,Corporate Services Contingent Labor Temp Labor...
4,2513,6050310,25.81,Fortune National Corp Miscellaneous Company Ca...

In [42]:
test.isna().sum()

Vendor_Code         0
GL_Code             0
Inv_Amt             0
Item_Description    0
dtype: int64

In [43]:
len(test)

2446

In [44]:
test = dataEncoder(test)

In [45]:
test.head()

,Vendor_Code,GL_Code,Inv_Amt,0,1,2,3,4,5,6,...,140,141,142,143,144,145,146,147,148,149
0,1513,3,56.13,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,44,7,96.56,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,-0.229416,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,254,7,55.93,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,-0.235702,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,331,0,32.62,0.0,0.0,0.0,0.0,0.0,0.0,0.176777,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,1513,3,25.81,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.182574,0.0,0.0,0.0

In [46]:
actual_test_prediction = gbm.predict(test)

In [47]:
#probability of classification
actual_test_prediction

array([[2.12555766e-09, 1.47574536e-08, 2.33749818e-08, ...,
        1.80717485e-09, 2.80203574e-09, 6.30855081e-09],
       [3.76372959e-09, 2.19466136e-08, 3.47158131e-08, ...,
        1.57976046e-09, 4.07393616e-09, 9.39351357e-09],
       [2.90240840e-09, 2.06470660e-08, 3.26605081e-08, ...,
        1.63950828e-09, 3.85487350e-09, 8.83421785e-09],
       ...,
       [1.41124105e-08, 4.18501838e-08, 9.99999159e-01, ...,
        3.01232345e-09, 7.81627432e-09, 1.84602806e-08],
       [8.18596946e-09, 5.81245015e-08, 9.19479992e-08, ...,
        4.18309158e-09, 1.09109006e-08, 2.48708236e-08],
       [1.69105050e-08, 9.62055792e-08, 1.53948456e-07, ...,
        6.87325492e-09, 1.85740140e-08, 4.10497991e-08]])

In [48]:
encoded_actual_test_prediction = [np.argmax(pred) for pred in actual_test_prediction]

In [49]:
inverse_transformed_prediction = Product_Category_Encoder.inverse_transform(encoded_actual_test_prediction)

In [50]:
data = {'Inv_Id': out_Inv_Id,'Product_Category':inverse_transformed_prediction}
output = pd.DataFrame(data) 
output['Product_Category'] = 'CLASS-'+output['Product_Category'].astype(str)

In [51]:
output.to_csv(r'Prediction_Output.csv', index=False)